apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-okta-demo
  name: spring-okta-demo
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: spring-okta-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-okta-demo
    spec:
      containers:
        - image: IMAGE_URL/spring-okta-demo:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: spring-okta-demo
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-okta-demo
  name: spring-okta-demo
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-okta-demo
  sessionAffinity: ClientIP
  type: LoadBalancer

