apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-okta-demo
  name: spring-okta-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-okta-demo
  template:
    metadata:
      labels:
        app: spring-okta-demo
    spec:
      containers:
      - image: IMAGE_URL/spring-okta-demo:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: spring-okta-demo
        ports:
          - containerPort: 9296
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-okta-demo
  name: spring-okta-demo
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 9296
  selector:
    app: spring-okta-demo
  sessionAffinity: ClientIP
  type: LoadBalancer

